turn_on:
  name: Turn on
  description:
    Set the light RGB and/or brightness based on the image provided by
    URL or file path.
  target:
    entity:
      domain: light
  fields:
    ambient_extract_url:
      name: URL
      description:
        The URL of the image we want to extract RGB values and brightness from. 
        Must be allowed in allowlist_external_urls.
      example: https://www.example.com/images/logo.png
      selector:
        text:
    ambient_extract_path:
      name: Path
      description:
        The full system path to the image we want to extract RGB values and
        brightness from.
        Must be allowed in allowlist_external_dirs.
      example: /opt/images/logo.png
      selector:
        text:
    brightness_min:
      name: Automatic brightness (minimal value)
      description:
        Auto Brightness lower boundary
      example: 5
      selector:
        number:
          min: 0
          max: 255
    brightness_max:
      name: Automatic brightness (maximal value)
      description:
        Auto Brightness upper boundary
      example: 25
      selector:
        number:
          min: 0
          max: 255
    brightness_auto:
      name: Auto Brightness on/off
      description: Adjust Brightness according to the image.
      example: True
      selector:
        boolean:
    brightness_mode:
      name: Brightness Mode
      description: How to calculate brightness
      example: natural
      selector:
        select:
          options:
            - mean
            - rms
            - natural
            - dominant
    rgb_temperature:
      name: RGB Color Temperature
      description: Let colors be warmer or colder -3<x<+3
      example: 0
      selector:
        number:
          min: -25
          max: 25
